/* version.c */
/* Autogenerated by Makefile - DO NOT EDIT */

const char *version_string = "1.15";
const char *compilation_string = "gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/usr/local/etc/wgetrc\" -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../lib -I../lib -g -O0";
const char *link_string = "gcc -g -O0 -lz -lrt ftp-opie.o ../lib/libgnu.a";
